### PR TITLE
[ODS-5686] Minimal template should include only include descriptors with ed-fi namespace

### PR DESCRIPTION
**Pull request by ericstockdale**
…riptors folder

### CODE REVIEW

**Review by semalaiappan — CHANGES_REQUESTED** [review]
Please use Rebuild Database Templates workflow to update packages version in ODS implementation .   Pre-requisties is you need to have ODS-5686 branch in ODS , ODS implementation and ODS Extension repo ,then run  Rebuild Database Templates workflow  from ODS-5686 branch . It will take 1 hour to update all packages automatically for you .  Note  Please clean up the existing manual package version what you have in ODS implementation repo of ODS-5686 branch.  All 3 branch needs to pushed to remote to execute  Rebuild Database Templates workflow .

**Comment by semalaiappan** [comment]
I downloaded EdFi.Suite3.Ods.Minimal.Template.7.0.541 package and I see data for data 
image
for [CreditCategoryDescriptor] example 
EdFi.Suite3.Ods.Minimal.Template.5.2.10570 - Release version

**Comment by ericstockdale** [comment]
Correct, there are ed-fi.org CreditCategoryDescriptor values, but there should no longer be Grandbend (gbisd.edu) namespace descriptors in the minimal template

image

**Comment by semalaiappan** [comment]
[edfi].[Descriptor] table should not have data for  Namespace like '%uri://gbisd.edu/%'

image

**Comment by semalaiappan** [comment]
now postgres also not have Namespace like '%uri://gbisd.edu/%' in 7.0.441 but  6.1 release has it .
image
image

**Review by semalaiappan — APPROVED** [review]

**Pull request merged**
