### PR TITLE
[ODS-5711] Switch workflows from windows-latest to ubuntu-latest

### PR DESCRIPTION
**Pull request by ericstockdale**

### CODE REVIEW

**Comment by semalaiappan** [comment]
Pkg EdFi.Ods.Minimal.Template.PostgreSQL less than 5 mins now 
image

**Comment by semalaiappan** [comment]
Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL is less than  5 mins now 
image

**Comment by semalaiappan** [comment]
Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL less than 8 mins now 
image

**Comment by semalaiappan** [comment]
This ticket changes looks good what ever Eric's changes  .  Only two things  I updated regarding  Install-credential-handler step 
[InstallCredentialHandler moved to build.githubactions file. so that easy to manage repeated code and also 
[Configure PostgreSQL using Docker image services to increase performance of PostgreSQL based template builds

**Review by simpat-jesus — APPROVED** [review]

**Pull request merged**
