### PR TITLE
[ODS-4022] Ed-Fi ODS/API availableChangeQueries OpenApi Spec definition is incorrect

### PR DESCRIPTION
**Pull request by blmeyers**
Adjusting metadata to match actual response for availableChangeVersions endpoint.

### CODE REVIEW

**Review by gmcelhanon — APPROVED** [review]
@blmeyers Build is failing, so I won't merge, but change is approved.

**Comment by gmcelhanon** [comment]
Build failure:
```
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\BuildAgent\work\904029b3fc87a31e\Ed-Fi-ODS-Implementation\logistics\scripts\modules\build-management.psm1:217
```

**Comment by blmeyers** [comment]
This branch didn't have the framework cleanup work, I rebased it on latest main and pushed it up, just need some time for the builds to run again.

**Comment by blmeyers** [comment]
@gmcelhanon Everything is building successfully now.

**Pull request merged**
